language: ruby
bundler_args: "--without development"
before_install:
  - gem install bundler
rvm:
  - jruby-19mode
  - 1.9.2
  - 1.9.3
  - 2.0.0
env:
    - JRUBY_OPTS="-Xcext.enabled=true"
script:
  - gem build aggcat.gemspec
  - gem install aggcat-*
